config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :application_settings
    resources :application_forms
  end

  resources :attachments
  resources :tickets
  devise_for :users

  resources :students do
    resources :selfies
  end

  resources :selfies, only: :index
  resources :groups

  get 'welcome/index'
  get 'welcome/rap'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_form.rb
class ApplicationForm < ApplicationRecord
  belongs_to :post
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :students, through: :memberships

  mount_uploader :cover, GroupCoverUploader

  acts_as_taggable
end

app/models/image.rb
class Image < Attachment
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :group
  belongs_to :student
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable_on :categories

  has_many :application_forms
  has_many :application_settings
end

app/models/selfie.rb
class Selfie < ApplicationRecord
  mount_uploader :image, SelfieUploader
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :selfies
  has_many :memberships
  has_many :groups, through: :memberships
  belongs_to :user, optional: true
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
end

app/models/tagging.rb
class Tagging < ActsAsTaggableOn::Tagging
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :reporter, class_name: 'User', foreign_key: 'reporter_id'
  belongs_to :doer, class_name: 'User', foreign_key: 'doer_id', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :student
  has_many :tickets_reported, class_name: 'Ticket', foreign_key: 'reporter_id', inverse_of: 'reporter'
  has_many :tickets_assigned, class_name: 'Ticket', foreign_key: 'doer_id', inverse_of: 'doer'

  after_create :create_student_profile

  def create_student_profile
    Student.create(user_id: self.id)
  end
end

app/models/video.rb
class Video < Attachment
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  before_action :set_application_form, only: [:show, :edit, :update, :destroy]

  # GET /application_forms
  # GET /application_forms.json
  def index
    @post = Post.find(params[:post_id])
    @application_forms = @post.application_forms
  end

  # GET /application_forms/1
  # GET /application_forms/1.json
  def show
  end

  # GET /application_forms/new
  def new
    @post = Post.find(params[:post_id])
    @application_setting = @post.application_settings.first
    @application_form = ApplicationForm.new
  end

  # GET /application_forms/1/edit
  def edit
  end

  # POST /application_forms
  # POST /application_forms.json
  def create
    @application_form = ApplicationForm.new(application_form_params)
    @application_form.post_id = params[:post_id]

    respond_to do |format|
      if @application_form.save
        format.html { redirect_to @application_form.post, notice: 'Application form was successfully created.' }
        format.json { render :show, status: :created, location: @application_form }
      else
        format.html { render :new }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_forms/1
  # PATCH/PUT /application_forms/1.json
  def update
    respond_to do |format|
      if @application_form.update(application_form_params)
        format.html { redirect_to @application_form, notice: 'Application form was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_form }
      else
        format.html { render :edit }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_forms/1
  # DELETE /application_forms/1.json
  def destroy
    @application_form.destroy
    respond_to do |format|
      format.html { redirect_to application_forms_url, notice: 'Application form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_form
      @application_form = ApplicationForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_form_params
      params.require(:application_form).permit(:name, :about, :email, :phone, :project_title, :project_description, :age, :post_id)
    end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/selfies_helper.rb
module SelfiesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application_forms/_form.html.erb
<%= form_with(model: [@post, application_form], local: true) do |form| %>
  <% if application_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application_form.errors.count, "error") %> prohibited this application_form from being saved:</h2>

      <ul>
        <% application_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @application_setting.name %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  <% end %>

  <% if @application_setting.about %>
    <div class="field">
      <%= form.label :about %>
      <%= form.text_area :about %>
    </div>
  <% end %>

  <% if @application_setting.email %>
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
  <% end %>

  <% if @application_setting.phone %>
    <div class="field">
      <%= form.label :phone %>
      <%= form.text_field :phone %>
    </div>
  <% end %>

  <% if @application_setting.project_title %>
    <div class="field">
      <%= form.label :project_title %>
      <%= form.text_field :project_title %>
    </div>
  <% end %>

  <% if @application_setting.project_description %>
    <div class="field">
      <%= form.label :project_description %>
      <%= form.text_area :project_description %>
    </div>
  <% end %>

  <% if @application_setting.age %>
    <div class="field">
      <%= form.label :age %>
      <%= form.number_field :age %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/application_forms/edit.html.erb
<h1>Editing Application Form</h1>

<%= render 'form', application_form: @application_form %>

<%= link_to 'Show', @application_form %> |
<%= link_to 'Back', application_forms_path %>

app/views/application_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Application Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Project title</th>
      <th>Project description</th>
      <th>Age</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @application_forms.each do |application_form| %>
      <tr>
        <td><%= application_form.name %></td>
        <td><%= application_form.about %></td>
        <td><%= application_form.email %></td>
        <td><%= application_form.phone %></td>
        <td><%= application_form.project_title %></td>
        <td><%= application_form.project_description %></td>
        <td><%= application_form.age %></td>
        <td><%= application_form.post_id %></td>
        <td><%= link_to 'Show', post_application_form_path(@post, application_form) %></td>
        <td><%= link_to 'Edit', edit_post_application_form_path(@post, application_form) %></td>
        <td><%#= link_to 'Destroy', application_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Application Form', new_application_form_path %>

app/views/application_forms/new.html.erb
<h1>New Application Form</h1>

<%= render 'form', application_form: @application_form %>

<%#= link_to 'Back', application_forms_path %>

app/views/application_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @application_form.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @application_form.about %>
</p>

<p>
  <strong>Email:</strong>
  <%= @application_form.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @application_form.phone %>
</p>

<p>
  <strong>Project title:</strong>
  <%= @application_form.project_title %>
</p>

<p>
  <strong>Project description:</strong>
  <%= @application_form.project_description %>
</p>

<p>
  <strong>Age:</strong>
  <%= @application_form.age %>
</p>

<p>
  <strong>Post:</strong>
  <%= @application_form.post_id %>
</p>

<%= link_to 'Edit', edit_application_form_path(@application_form) %> |
<%= link_to 'Back', application_forms_path %>