config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :application_settings
    resources :application_forms
  end

  resources :attachments
  resources :tickets
  devise_for :users

  resources :students do
    resources :selfies
  end

  resources :selfies, only: :index
  resources :groups

  get 'welcome/index'
  get 'welcome/rap'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_form.rb
class ApplicationForm < ApplicationRecord
  belongs_to :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :students, through: :memberships

  mount_uploader :cover, GroupCoverUploader

  acts_as_taggable
end

app/models/image.rb
class Image < Attachment
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :group
  belongs_to :student
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable_on :categories

  has_many :application_forms
  has_many :application_settings
end

app/models/selfie.rb
class Selfie < ApplicationRecord
  mount_uploader :image, SelfieUploader
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :selfies
  has_many :memberships
  has_many :groups, through: :memberships
  belongs_to :user, optional: true
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
end

app/models/tagging.rb
class Tagging < ActsAsTaggableOn::Tagging
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :reporter, class_name: 'User', foreign_key: 'reporter_id'
  belongs_to :doer, class_name: 'User', foreign_key: 'doer_id', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :student
  has_many :tickets_reported, class_name: 'Ticket', foreign_key: 'reporter_id', inverse_of: 'reporter'
  has_many :tickets_assigned, class_name: 'Ticket', foreign_key: 'doer_id', inverse_of: 'doer'

  after_create :create_student_profile

  def create_student_profile
    Student.create(user_id: self.id)
  end
end

app/models/video.rb
class Video < Attachment
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:type, :url)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/selfies_helper.rb
module SelfiesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attachments/_attachment.html.erb
<%= attachment.url %>

app/views/attachments/_form.html.erb
<%= form_with(model: attachment, local: true) do |form| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
        <% attachment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>


<% @attachments.each do |attachment| %>
  <%= render attachment %>

  <%= link_to 'Show', attachment_path(attachment) %>
  <%= link_to 'Edit', edit_attachment_path(attachment) %>
  <%= link_to 'Destroy', attachment_path(attachment), method: :delete, data: { confirm: 'Are you sure?' } %>

  <br>
<% end %>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @attachment.type %>
</p>

<p>
  <strong>Url:</strong>
  <%= @attachment.url %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>